# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-05 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WxClick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip', models.CharField(max_length=20)),
                ('ua', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WxShareURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clicks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WxURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WxUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wx_id', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=64, null=True)),
                ('avatar', models.CharField(max_length=255, null=True)),
                ('sex', models.IntegerField()),
                ('country', models.CharField(max_length=20, null=True)),
                ('province', models.CharField(max_length=20, null=True)),
                ('city', models.CharField(max_length=20, null=True)),
                ('admin', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='wxshareurl',
            name='wx_url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.WxURL'),
        ),
        migrations.AddField(
            model_name='wxshareurl',
            name='wx_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.WxUser'),
        ),
        migrations.AddField(
            model_name='wxclick',
            name='wx_share_url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.WxShareURL'),
        ),
    ]
