# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-05 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wxurl',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='标题'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wxurl',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='wxurl',
            name='url',
            field=models.CharField(max_length=255, verbose_name='链接'),
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='admin',
            field=models.IntegerField(verbose_name='是否管理员'),
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='avatar',
            field=models.CharField(max_length=255, null=True, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='city',
            field=models.CharField(max_length=20, null=True, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='country',
            field=models.CharField(max_length=20, null=True, verbose_name='国家'),
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='name',
            field=models.CharField(max_length=64, null=True, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='province',
            field=models.CharField(max_length=20, null=True, verbose_name='省份'),
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='sex',
            field=models.IntegerField(verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='wx_id',
            field=models.CharField(max_length=64, unique=True, verbose_name='用户的微信ID'),
        ),
    ]
