# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-05 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170505_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='wxshareurl',
            name='friend_shares',
            field=models.IntegerField(default=0, verbose_name='好友、群分享数'),
        ),
        migrations.AddField(
            model_name='wxshareurl',
            name='timeline_shares',
            field=models.IntegerField(default=0, verbose_name='朋友圈分享数'),
        ),
        migrations.AddField(
            model_name='wxurl',
            name='image',
            field=models.CharField(max_length=255, null=True, verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='wxshareurl',
            name='clicks',
            field=models.IntegerField(default=0, verbose_name='点击数'),
        ),
    ]
