# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-06 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170505_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='wxurl',
            name='memo',
            field=models.CharField(default='', max_length=255, verbose_name='分享文案'),
        ),
    ]
