# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-06 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_wxurl_memo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wxclick',
            options={'verbose_name': '点击记录', 'verbose_name_plural': '点击列表'},
        ),
        migrations.AlterModelOptions(
            name='wxshareurl',
            options={'verbose_name': '文章分享', 'verbose_name_plural': '文章分享列表'},
        ),
        migrations.AlterModelOptions(
            name='wxurl',
            options={'verbose_name': '文章', 'verbose_name_plural': '文章列表'},
        ),
        migrations.AlterField(
            model_name='wxclick',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='wxclick',
            name='ip',
            field=models.CharField(max_length=20, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='wxclick',
            name='ua',
            field=models.CharField(max_length=255, verbose_name='客户端'),
        ),
        migrations.AlterField(
            model_name='wxclick',
            name='uuid',
            field=models.CharField(default='', max_length=64, verbose_name='用户唯一ID'),
        ),
        migrations.AlterField(
            model_name='wxshareurl',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
