# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-07 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170507_0021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wxurl',
            options={'verbose_name': '文章', 'verbose_name_plural': ' 文章列表'},
        ),
        migrations.AlterField(
            model_name='wxclick',
            name='wx_share_url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.WxShareURL', verbose_name='分享的文章'),
        ),
        migrations.AlterField(
            model_name='wxshareurl',
            name='wx_url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.WxURL', verbose_name='文章'),
        ),
        migrations.AlterField(
            model_name='wxshareurl',
            name='wx_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.WxUser', verbose_name='用户'),
        ),
    ]
